Models/CRUDContext.cs
    using Microsoft.EntityFrameworkCore; 
    namespace CRUDelicious.Models
    {
        public class CRUDContext : DbContext
        {
            public CRUDContext(DbContextOptions<CRUDContext> options) : base(options) { }
        
            public DbSet<Dishes> dishes {get;set;}
            public DbSet<Chef> chefs {get;set;}
        }
    }
    

Models/Chef.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRUDelicious.Models
{
    public class Chef
    {
        [Key]
        public int ChefId {get; set;}
        [Required]
        [MinLength(3)]
        public string FirstName {get;set;}
        [Required]
        [MinLength(3)]
        public string LastName {get;set;}
        [Required]
        public DateTime Age {get; set;}

        public List<Dishes> Dishes {get; set;}

        [NotMapped]
        public int DoB {get; set;}
    }
}

Models/Dishes.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CRUDelicious.Models
{
    public class Dishes
    {
        [Key]
        public int DishId {get;  set;}
        [Required]
        [MinLength(4)]
        public string Name {get; set;}
        public int Tastiness {get; set;}
        public int Calories {get; set;}
        public string Description {get; set;}

        public int ChefId {get;set;}

        public Chef Chef {get;set;}
    }
}

Controllers/DishesController.cs
using Microsoft.EntityFrameworkCore;
using CRUDelicious.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;

namespace CRUDelicious.Controllers
{
    public class DishesController : Controller
    {
        private CRUDContext dbContext;
        public DishesController(CRUDContext context)
        {
            dbContext = context;
        }
     
        [HttpGet("")]
        public IActionResult Index()
        {
            List<Chef> AllChefs = dbContext.chefs.Include(u=> u.Dishes).ToList();
            foreach(var x in AllChefs)
            {
                var now = DateTime.Today;
                var chefAge = x.Age - now;
                string strChef = chefAge.ToString("%d");
                int intChef = Int32.Parse(strChef);
                intChef /= 365;
                x.DoB = intChef;

            }
            ViewBag.Chefs = AllChefs;
            return View("index");
        }

        [HttpGet("dishes")]
        public IActionResult Dishes()
        {
            List<Dishes> AllDishes= dbContext.dishes.Include(u=> u.Chef).ToList();
            ViewBag.Dishes = AllDishes;
            return View("dishes");
        }
        [HttpGet("new")]
        public IActionResult New()
        {
            return View("new");
        }

        [HttpGet("dishes/new")]
        public IActionResult NewDish()
        {
            List<Chef> AllChefs = dbContext.chefs.ToList();
            ViewBag.Chefs = AllChefs;
            return View("newdish");
        }
        
        [HttpPost("addchef")]
        public IActionResult AddChef(Chef chef)
        {
            if(ModelState.IsValid)
            {
                var now = DateTime.Today;
                var chefAge = now - chef.Age;
                DateTime day1 = new DateTime(2018,1,1);
                DateTime day2 = new DateTime(2000,1,1);
                var eighteen = day1 - day2;
                if(chefAge > eighteen){
                    dbContext.Add(chef);
                    dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Age" , "Age should be minimum 18");
                    return View("new");
                }
                
            }
            else
            {
                return View("new");
            }
           
        }

        [HttpPost("create/dish")]
        public IActionResult CreateDish(Dishes dish)
        {
            if(ModelState.IsValid)
            {
                dbContext.Add(dish);
                dbContext.SaveChanges();
                return RedirectToAction("dishes");
            }
            else
            {
                List<Chef> AllChefs = dbContext.chefs.ToList();
                ViewBag.Chefs = AllChefs;
                return View("newdish");
            }
           
        }
    }
}

Views/Dishes/dishes.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Dishes</title>
</head>
<body>
    <h1><a href="/">Chefs</a> | Dishes</h1>
    <a href="/dishes/new">Add a Dish</a>
    <hr>
     <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Chef</th>
                <th scope="col">Tastiness</th>
                <th scope="col">Calories</th>
            </tr>
        </thead>
        <tbody>
            @{
                @foreach(var x in ViewBag.Dishes)
                {
                    <tr>
                        <th scope="row">@x.Name</th>
                        <td>@x.Chef.FirstName  @x.Chef.LastName</td>
                        <td>@x.Tastiness</td>
                        <td>@x.Calories</td>
                    </tr>
                }

            }
        </tbody>
    </table>
</body>
</html>

Views/Dishes/index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Chefs</title>
</head>
<body>
    <h1>Chefs | <a href="/dishes">Dishes</a></h1>
    <a href="/new">Add a Chef</a>
    <hr>
     <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col"># of dishes</th>
    </tr>
  </thead>
  <tbody>
   @{
     foreach(var x in ViewBag.Chefs)
     {
      <tr>
        <th scope="row">@x.FirstName  @x.LastName</th>
        <td>@x.DoB</td>
        <td>@x.Dishes.Count</td>
      </tr>
     }
   }
  </tbody>
</table>
</body>
</html>

Views/Dishes/new.cshtml
@model Chef
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add chef</title>
</head>
<body>
    <a href="/">Home</a>
    <form asp-controller="Dishes" asp-action="AddChef" method="POST">
            <span asp-validation-for="FirstName"></span>
            <h1>First Name: <input type="text" asp-for="FirstName"> </h1>
            <span asp-validation-for="LastName"></span>
            <h1>Last Name : <input type="text" asp-for="LastName"> </h1>
            <span asp-validation-for="Age"></span>
            <h1>Age : <input type="date" asp-for="Age"> </h1>
            <input type="submit" value ="Add Chef">
    </form>
</body>
</html>

Views/Dishes/newdish.cshtml
@model Dishes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Dish</title>
</head>
<body>
    <a href="/dishes">Home</a>
    <form asp-controller="Dishes" asp-action="CreateDish" method="POST">
            <span asp-validation-for="Name"></span>
            <h1>Name: <input type="text" asp-for="Name"> </h1>
            <h1>Tastiness : <select asp-for="Tastiness" > 
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select></h1>
            <h1>Calories : <input type="text" asp-for="Calories"> </h1>
            <h1>Description : <input type="text" asp-for="Description"> </h1>
            <h1>Chef : <select asp-for="ChefId" >
                @{
                    foreach(var x in ViewBag.Chefs)
                    {
                       <option value="@x.ChefId">@x.FirstName  @x.LastName</option>
                    }
                }
            </select></h1>
            <input type="submit" value ="Add Dish">
    </form>
</body>
</html>